name: Run Daily Scrapper
on:
  schedule:
    - cron:  "20 15 * * *"
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
    # - name: Get ENV Secrets
    #   run: |
    #     echo "TG_API_HASH: ${{ secrets.TG_API_HASH }}"
    #     echo "TG_API_ID: ${{ secrets.TG_API_ID }}"
    #     echo "TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}"
    #     echo "TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}"
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Python app
      env:
        TG_API_HASH: ${{ secrets.TG_API_HASH }}
        TG_API_ID: ${{ secrets.TG_API_ID }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
      run: |
        python main.py
