name: Run Test Scrapper
on:
  # schedule:
  #   - cron:  "20 15 * * *"
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WB_UPDATE }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
      
    - name: Run Poetry  
      run: |
        poetry --version
        cd $GITHUB_WORKSPACE
        poetry install
          
    - name: Run Python app
      env:
        TG_API_HASH: ${{ secrets.TG_API_HASH }}
        TG_API_ID: ${{ secrets.TG_API_ID }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_PRI_ID }}
      run: |
        poetry shell
        python main.py
    
    - name: Add log files to repo
      run: |
        echo "Adding logs to Git..."
        git add logs

    - name: Check for changes
      id: check_changes
      run: |
        git diff-index --quiet HEAD || echo "::set-output name=changes::true"

    - name: Commit changes
      run: |
        echo "Checking changes to Git..."
        git config user.name github-actions
        git config user.email github-actions@github.com
        if [[ ${{ steps.check_changes.outputs.changes }} == "true" ]]; then
          echo "Changes registered commit & push"
          git commit -m "Log update `date +'%d-%m-%Y %H:%M:%S'`"
          git push
        else
          echo "No changes to commit."