name: Run Test Scrapper
on:
  # schedule:
  #   - cron:  "20 15 * * *"
  workflow_dispatch:

jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WB_UPDATE }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Python app
      env:
        TG_API_HASH: ${{ secrets.TG_API_HASH }}
        TG_API_ID: ${{ secrets.TG_API_ID }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_PRI_ID }}
      run: |
        python main.py
    
    - name: Add log files to repo
      run: |
        echo "Adding logs to Git..."
        git add logs

    - name: Commit changes
      run: |
        echo "Committing changes to Git..."
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Log update `date +'%d-%m-%Y %H:%M:%S'`"

    - name: Push changes to the same branch
      run: |
        git push